apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base

patches:
  - path: patch-configmap.yaml

images:
  - name: demo-app
    newName: REPLACE_WITH_YOUR_ECR_URL
    newTag: 0.1.0