apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patch-configmap.yaml

images:
  - name: demo-app
    newName: 944053746993.dkr.ecr.us-east-2.amazonaws.com/ct-gitops/demo-app
    newTag: 0.1.0